#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040028
			public const int about_text = 2130968616;
			
			// aapt resource value: 0x7f040026
			public const int about_title = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int about_version = 2130968615;
			
			// aapt resource value: 0x7f040009
			public const int action_about = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int action_connect = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int action_disconnect = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int action_select = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int action_settings = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int battery = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int cancel = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int drawer_close = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int drawer_open = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int drawer_plugin_nrf_connect = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int drawer_plugins = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int font_path = 2130968579;
			
			// aapt resource value: 0x7f040023
			public const int log = 2130968611;
			
			// aapt resource value: 0x7f040007
			public const int no = 2130968583;
			
			// aapt resource value: 0x7f040018
			public const int no_application = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int no_application_play = 2130968602;
			
			// aapt resource value: 0x7f040016
			public const int no_apps = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int no_ble = 2130968597;
			
			// aapt resource value: 0x7f04001b
			public const int no_required_permission = 2130968603;
			
			// aapt resource value: 0x7f040019
			public const int no_uri_application = 2130968601;
			
			// aapt resource value: 0x7f040004
			public const int normal_font_path = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int not_available = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int not_available_value = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int not_supported = 2130968599;
			
			// aapt resource value: 0x7f040005
			public const int ok = 2130968581;
			
			// aapt resource value: 0x7f040025
			public const int permission_sd_text = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int permission_title = 2130968612;
			
			// aapt resource value: 0x7f04001f
			public const int scanner_action_cancel = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int scanner_action_scan = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int scanner_empty = 2130968605;
			
			// aapt resource value: 0x7f040022
			public const int scanner_permission_rationale = 2130968610;
			
			// aapt resource value: 0x7f040020
			public const int scanner_subtitle_bonded = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int scanner_subtitle_not_bonded = 2130968609;
			
			// aapt resource value: 0x7f04001c
			public const int scanner_title = 2130968604;
			
			// aapt resource value: 0x7f04002a
			public const int view_btn_off = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int view_btn_on = 2130968617;
			
			// aapt resource value: 0x7f040006
			public const int yes = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
